/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LeaveApprovalHistory service. Represents a row in the &quot;LeaveApprovalHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.LeaveApprovalHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.LeaveApprovalHistoryImpl}.
 * </p>
 *
 * @author
 * @see LeaveApprovalHistory
 * @see com.trianz.lms.model.impl.LeaveApprovalHistoryImpl
 * @see com.trianz.lms.model.impl.LeaveApprovalHistoryModelImpl
 * @generated
 */
public interface LeaveApprovalHistoryModel extends BaseModel<LeaveApprovalHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave approval history model instance should use the {@link LeaveApprovalHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this leave approval history.
	 *
	 * @return the primary key of this leave approval history
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this leave approval history.
	 *
	 * @param primaryKey the primary key of this leave approval history
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the s no of this leave approval history.
	 *
	 * @return the s no of this leave approval history
	 */
	public int getSNo();

	/**
	 * Sets the s no of this leave approval history.
	 *
	 * @param SNo the s no of this leave approval history
	 */
	public void setSNo(int SNo);

	/**
	 * Returns the leave request ID of this leave approval history.
	 *
	 * @return the leave request ID of this leave approval history
	 */
	@AutoEscape
	public String getLeaveRequestId();

	/**
	 * Sets the leave request ID of this leave approval history.
	 *
	 * @param LeaveRequestId the leave request ID of this leave approval history
	 */
	public void setLeaveRequestId(String LeaveRequestId);

	/**
	 * Returns the approver i d of this leave approval history.
	 *
	 * @return the approver i d of this leave approval history
	 */
	public int getApproverID();

	/**
	 * Sets the approver i d of this leave approval history.
	 *
	 * @param ApproverID the approver i d of this leave approval history
	 */
	public void setApproverID(int ApproverID);

	/**
	 * Returns the leave status of this leave approval history.
	 *
	 * @return the leave status of this leave approval history
	 */
	@AutoEscape
	public String getLeaveStatus();

	/**
	 * Sets the leave status of this leave approval history.
	 *
	 * @param LeaveStatus the leave status of this leave approval history
	 */
	public void setLeaveStatus(String LeaveStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LeaveApprovalHistory leaveApprovalHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LeaveApprovalHistory> toCacheModel();

	@Override
	public LeaveApprovalHistory toEscapedModel();

	@Override
	public LeaveApprovalHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}