/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LeaveCategories service. Represents a row in the &quot;LeaveCategories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.LeaveCategoriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.LeaveCategoriesImpl}.
 * </p>
 *
 * @author
 * @see LeaveCategories
 * @see com.trianz.lms.model.impl.LeaveCategoriesImpl
 * @see com.trianz.lms.model.impl.LeaveCategoriesModelImpl
 * @generated
 */
public interface LeaveCategoriesModel extends BaseModel<LeaveCategories> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave categories model instance should use the {@link LeaveCategories} interface instead.
	 */

	/**
	 * Returns the primary key of this leave categories.
	 *
	 * @return the primary key of this leave categories
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this leave categories.
	 *
	 * @param primaryKey the primary key of this leave categories
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the leave category code of this leave categories.
	 *
	 * @return the leave category code of this leave categories
	 */
	@AutoEscape
	public String getLeaveCategoryCode();

	/**
	 * Sets the leave category code of this leave categories.
	 *
	 * @param LeaveCategoryCode the leave category code of this leave categories
	 */
	public void setLeaveCategoryCode(String LeaveCategoryCode);

	/**
	 * Returns the leave category of this leave categories.
	 *
	 * @return the leave category of this leave categories
	 */
	@AutoEscape
	public String getLeaveCategory();

	/**
	 * Sets the leave category of this leave categories.
	 *
	 * @param LeaveCategory the leave category of this leave categories
	 */
	public void setLeaveCategory(String LeaveCategory);

	/**
	 * Returns the leave type code of this leave categories.
	 *
	 * @return the leave type code of this leave categories
	 */
	public int getLeaveTypeCode();

	/**
	 * Sets the leave type code of this leave categories.
	 *
	 * @param LeaveTypeCode the leave type code of this leave categories
	 */
	public void setLeaveTypeCode(int LeaveTypeCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LeaveCategories leaveCategories);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LeaveCategories> toCacheModel();

	@Override
	public LeaveCategories toEscapedModel();

	@Override
	public LeaveCategories toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}