/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.trianz.lms.service.persistence.LMSCompOffLeaveDetailsPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LMSCompOffLeaveDetails service. Represents a row in the &quot;LMSCompOffLeaveDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.LMSCompOffLeaveDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.LMSCompOffLeaveDetailsImpl}.
 * </p>
 *
 * @author
 * @see LMSCompOffLeaveDetails
 * @see com.trianz.lms.model.impl.LMSCompOffLeaveDetailsImpl
 * @see com.trianz.lms.model.impl.LMSCompOffLeaveDetailsModelImpl
 * @generated
 */
public interface LMSCompOffLeaveDetailsModel extends BaseModel<LMSCompOffLeaveDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l m s comp off leave details model instance should use the {@link LMSCompOffLeaveDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this l m s comp off leave details.
	 *
	 * @return the primary key of this l m s comp off leave details
	 */
	public LMSCompOffLeaveDetailsPK getPrimaryKey();

	/**
	 * Sets the primary key of this l m s comp off leave details.
	 *
	 * @param primaryKey the primary key of this l m s comp off leave details
	 */
	public void setPrimaryKey(LMSCompOffLeaveDetailsPK primaryKey);

	/**
	 * Returns the approved by of this l m s comp off leave details.
	 *
	 * @return the approved by of this l m s comp off leave details
	 */
	@AutoEscape
	public String getApprovedBy();

	/**
	 * Sets the approved by of this l m s comp off leave details.
	 *
	 * @param ApprovedBy the approved by of this l m s comp off leave details
	 */
	public void setApprovedBy(String ApprovedBy);

	/**
	 * Returns the created date of this l m s comp off leave details.
	 *
	 * @return the created date of this l m s comp off leave details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this l m s comp off leave details.
	 *
	 * @param CreatedDate the created date of this l m s comp off leave details
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the employee i d of this l m s comp off leave details.
	 *
	 * @return the employee i d of this l m s comp off leave details
	 */
	public int getEmployeeID();

	/**
	 * Sets the employee i d of this l m s comp off leave details.
	 *
	 * @param EmployeeID the employee i d of this l m s comp off leave details
	 */
	public void setEmployeeID(int EmployeeID);

	/**
	 * Returns the status of this l m s comp off leave details.
	 *
	 * @return the status of this l m s comp off leave details
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this l m s comp off leave details.
	 *
	 * @param Status the status of this l m s comp off leave details
	 */
	public void setStatus(String Status);

	/**
	 * Returns the compoff date of this l m s comp off leave details.
	 *
	 * @return the compoff date of this l m s comp off leave details
	 */
	public Date getCompoffDate();

	/**
	 * Sets the compoff date of this l m s comp off leave details.
	 *
	 * @param CompoffDate the compoff date of this l m s comp off leave details
	 */
	public void setCompoffDate(Date CompoffDate);

	/**
	 * Returns the comp off ID of this l m s comp off leave details.
	 *
	 * @return the comp off ID of this l m s comp off leave details
	 */
	public int getCompOffId();

	/**
	 * Sets the comp off ID of this l m s comp off leave details.
	 *
	 * @param CompOffId the comp off ID of this l m s comp off leave details
	 */
	public void setCompOffId(int CompOffId);

	/**
	 * Returns the approver employee i d of this l m s comp off leave details.
	 *
	 * @return the approver employee i d of this l m s comp off leave details
	 */
	public int getApproverEmployeeID();

	/**
	 * Sets the approver employee i d of this l m s comp off leave details.
	 *
	 * @param ApproverEmployeeID the approver employee i d of this l m s comp off leave details
	 */
	public void setApproverEmployeeID(int ApproverEmployeeID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LMSCompOffLeaveDetails lmsCompOffLeaveDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LMSCompOffLeaveDetails> toCacheModel();

	@Override
	public LMSCompOffLeaveDetails toEscapedModel();

	@Override
	public LMSCompOffLeaveDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}