/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LMSEmployeeDetails service. Represents a row in the &quot;LMSEmployeeDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.LMSEmployeeDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.LMSEmployeeDetailsImpl}.
 * </p>
 *
 * @author
 * @see LMSEmployeeDetails
 * @see com.trianz.lms.model.impl.LMSEmployeeDetailsImpl
 * @see com.trianz.lms.model.impl.LMSEmployeeDetailsModelImpl
 * @generated
 */
public interface LMSEmployeeDetailsModel extends BaseModel<LMSEmployeeDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l m s employee details model instance should use the {@link LMSEmployeeDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this l m s employee details.
	 *
	 * @return the primary key of this l m s employee details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this l m s employee details.
	 *
	 * @param primaryKey the primary key of this l m s employee details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the employee ID of this l m s employee details.
	 *
	 * @return the employee ID of this l m s employee details
	 */
	public int getEmployeeId();

	/**
	 * Sets the employee ID of this l m s employee details.
	 *
	 * @param EmployeeId the employee ID of this l m s employee details
	 */
	public void setEmployeeId(int EmployeeId);

	/**
	 * Returns the employee name of this l m s employee details.
	 *
	 * @return the employee name of this l m s employee details
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this l m s employee details.
	 *
	 * @param EmployeeName the employee name of this l m s employee details
	 */
	public void setEmployeeName(String EmployeeName);

	/**
	 * Returns the employee email i d of this l m s employee details.
	 *
	 * @return the employee email i d of this l m s employee details
	 */
	@AutoEscape
	public String getEmployeeEmailID();

	/**
	 * Sets the employee email i d of this l m s employee details.
	 *
	 * @param EmployeeEmailID the employee email i d of this l m s employee details
	 */
	public void setEmployeeEmailID(String EmployeeEmailID);

	/**
	 * Returns the joining date of this l m s employee details.
	 *
	 * @return the joining date of this l m s employee details
	 */
	public Date getJoiningDate();

	/**
	 * Sets the joining date of this l m s employee details.
	 *
	 * @param JoiningDate the joining date of this l m s employee details
	 */
	public void setJoiningDate(Date JoiningDate);

	/**
	 * Returns the supervisor ID of this l m s employee details.
	 *
	 * @return the supervisor ID of this l m s employee details
	 */
	public int getSupervisorId();

	/**
	 * Sets the supervisor ID of this l m s employee details.
	 *
	 * @param SupervisorId the supervisor ID of this l m s employee details
	 */
	public void setSupervisorId(int SupervisorId);

	/**
	 * Returns the supervisor name of this l m s employee details.
	 *
	 * @return the supervisor name of this l m s employee details
	 */
	@AutoEscape
	public String getSupervisorName();

	/**
	 * Sets the supervisor name of this l m s employee details.
	 *
	 * @param SupervisorName the supervisor name of this l m s employee details
	 */
	public void setSupervisorName(String SupervisorName);

	/**
	 * Returns the supervisor email of this l m s employee details.
	 *
	 * @return the supervisor email of this l m s employee details
	 */
	@AutoEscape
	public String getSupervisorEmail();

	/**
	 * Sets the supervisor email of this l m s employee details.
	 *
	 * @param SupervisorEmail the supervisor email of this l m s employee details
	 */
	public void setSupervisorEmail(String SupervisorEmail);

	/**
	 * Returns the location of this l m s employee details.
	 *
	 * @return the location of this l m s employee details
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this l m s employee details.
	 *
	 * @param Location the location of this l m s employee details
	 */
	public void setLocation(String Location);

	/**
	 * Returns the region of this l m s employee details.
	 *
	 * @return the region of this l m s employee details
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this l m s employee details.
	 *
	 * @param Region the region of this l m s employee details
	 */
	public void setRegion(String Region);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LMSEmployeeDetails lmsEmployeeDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LMSEmployeeDetails> toCacheModel();

	@Override
	public LMSEmployeeDetails toEscapedModel();

	@Override
	public LMSEmployeeDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}