/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LMSLeaveInformation service. Represents a row in the &quot;LMSLeaveInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.LMSLeaveInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.LMSLeaveInformationImpl}.
 * </p>
 *
 * @author
 * @see LMSLeaveInformation
 * @see com.trianz.lms.model.impl.LMSLeaveInformationImpl
 * @see com.trianz.lms.model.impl.LMSLeaveInformationModelImpl
 * @generated
 */
public interface LMSLeaveInformationModel extends BaseModel<LMSLeaveInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l m s leave information model instance should use the {@link LMSLeaveInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this l m s leave information.
	 *
	 * @return the primary key of this l m s leave information
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this l m s leave information.
	 *
	 * @param primaryKey the primary key of this l m s leave information
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the s no of this l m s leave information.
	 *
	 * @return the s no of this l m s leave information
	 */
	public int getSNo();

	/**
	 * Sets the s no of this l m s leave information.
	 *
	 * @param SNo the s no of this l m s leave information
	 */
	public void setSNo(int SNo);

	/**
	 * Returns the leave request ID of this l m s leave information.
	 *
	 * @return the leave request ID of this l m s leave information
	 */
	@AutoEscape
	public String getLeaveRequestId();

	/**
	 * Sets the leave request ID of this l m s leave information.
	 *
	 * @param LeaveRequestId the leave request ID of this l m s leave information
	 */
	public void setLeaveRequestId(String LeaveRequestId);

	/**
	 * Returns the employee ID of this l m s leave information.
	 *
	 * @return the employee ID of this l m s leave information
	 */
	public int getEmployeeId();

	/**
	 * Sets the employee ID of this l m s leave information.
	 *
	 * @param EmployeeId the employee ID of this l m s leave information
	 */
	public void setEmployeeId(int EmployeeId);

	/**
	 * Returns the absence type of this l m s leave information.
	 *
	 * @return the absence type of this l m s leave information
	 */
	@AutoEscape
	public String getAbsenceType();

	/**
	 * Sets the absence type of this l m s leave information.
	 *
	 * @param AbsenceType the absence type of this l m s leave information
	 */
	public void setAbsenceType(String AbsenceType);

	/**
	 * Returns the leave type code of this l m s leave information.
	 *
	 * @return the leave type code of this l m s leave information
	 */
	public int getLeaveTypeCode();

	/**
	 * Sets the leave type code of this l m s leave information.
	 *
	 * @param LeaveTypeCode the leave type code of this l m s leave information
	 */
	public void setLeaveTypeCode(int LeaveTypeCode);

	/**
	 * Returns the leave category code of this l m s leave information.
	 *
	 * @return the leave category code of this l m s leave information
	 */
	@AutoEscape
	public String getLeaveCategoryCode();

	/**
	 * Sets the leave category code of this l m s leave information.
	 *
	 * @param LeaveCategoryCode the leave category code of this l m s leave information
	 */
	public void setLeaveCategoryCode(String LeaveCategoryCode);

	/**
	 * Returns the supervisor i d of this l m s leave information.
	 *
	 * @return the supervisor i d of this l m s leave information
	 */
	public int getSupervisorID();

	/**
	 * Sets the supervisor i d of this l m s leave information.
	 *
	 * @param SupervisorID the supervisor i d of this l m s leave information
	 */
	public void setSupervisorID(int SupervisorID);

	/**
	 * Returns the start date of this l m s leave information.
	 *
	 * @return the start date of this l m s leave information
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this l m s leave information.
	 *
	 * @param StartDate the start date of this l m s leave information
	 */
	public void setStartDate(Date StartDate);

	/**
	 * Returns the end date of this l m s leave information.
	 *
	 * @return the end date of this l m s leave information
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this l m s leave information.
	 *
	 * @param EndDate the end date of this l m s leave information
	 */
	public void setEndDate(Date EndDate);

	/**
	 * Returns the duration of this l m s leave information.
	 *
	 * @return the duration of this l m s leave information
	 */
	public double getDuration();

	/**
	 * Sets the duration of this l m s leave information.
	 *
	 * @param Duration the duration of this l m s leave information
	 */
	public void setDuration(double Duration);

	/**
	 * Returns the approval status of this l m s leave information.
	 *
	 * @return the approval status of this l m s leave information
	 */
	@AutoEscape
	public String getApprovalStatus();

	/**
	 * Sets the approval status of this l m s leave information.
	 *
	 * @param ApprovalStatus the approval status of this l m s leave information
	 */
	public void setApprovalStatus(String ApprovalStatus);

	/**
	 * Returns the comments of this l m s leave information.
	 *
	 * @return the comments of this l m s leave information
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this l m s leave information.
	 *
	 * @param Comments the comments of this l m s leave information
	 */
	public void setComments(String Comments);

	/**
	 * Returns the is draft of this l m s leave information.
	 *
	 * @return the is draft of this l m s leave information
	 */
	@AutoEscape
	public String getIsDraft();

	/**
	 * Sets the is draft of this l m s leave information.
	 *
	 * @param isDraft the is draft of this l m s leave information
	 */
	public void setIsDraft(String isDraft);

	/**
	 * Returns the approvers of this l m s leave information.
	 *
	 * @return the approvers of this l m s leave information
	 */
	public int getApprovers();

	/**
	 * Sets the approvers of this l m s leave information.
	 *
	 * @param Approvers the approvers of this l m s leave information
	 */
	public void setApprovers(int Approvers);

	/**
	 * Returns the created date of this l m s leave information.
	 *
	 * @return the created date of this l m s leave information
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this l m s leave information.
	 *
	 * @param CreatedDate the created date of this l m s leave information
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the approver emails of this l m s leave information.
	 *
	 * @return the approver emails of this l m s leave information
	 */
	@AutoEscape
	public String getApproverEmails();

	/**
	 * Sets the approver emails of this l m s leave information.
	 *
	 * @param ApproverEmails the approver emails of this l m s leave information
	 */
	public void setApproverEmails(String ApproverEmails);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LMSLeaveInformation lmsLeaveInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LMSLeaveInformation> toCacheModel();

	@Override
	public LMSLeaveInformation toEscapedModel();

	@Override
	public LMSLeaveInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}