/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LMSMailNotifications service. Represents a row in the &quot;LMSMailNotifications&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.LMSMailNotificationsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.LMSMailNotificationsImpl}.
 * </p>
 *
 * @author
 * @see LMSMailNotifications
 * @see com.trianz.lms.model.impl.LMSMailNotificationsImpl
 * @see com.trianz.lms.model.impl.LMSMailNotificationsModelImpl
 * @generated
 */
public interface LMSMailNotificationsModel extends BaseModel<LMSMailNotifications> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l m s mail notifications model instance should use the {@link LMSMailNotifications} interface instead.
	 */

	/**
	 * Returns the primary key of this l m s mail notifications.
	 *
	 * @return the primary key of this l m s mail notifications
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this l m s mail notifications.
	 *
	 * @param primaryKey the primary key of this l m s mail notifications
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the mail notfn ID of this l m s mail notifications.
	 *
	 * @return the mail notfn ID of this l m s mail notifications
	 */
	public int getMailNotfnId();

	/**
	 * Sets the mail notfn ID of this l m s mail notifications.
	 *
	 * @param MailNotfnId the mail notfn ID of this l m s mail notifications
	 */
	public void setMailNotfnId(int MailNotfnId);

	/**
	 * Returns the leave request ID of this l m s mail notifications.
	 *
	 * @return the leave request ID of this l m s mail notifications
	 */
	@AutoEscape
	public String getLeaveRequestId();

	/**
	 * Sets the leave request ID of this l m s mail notifications.
	 *
	 * @param LeaveRequestId the leave request ID of this l m s mail notifications
	 */
	public void setLeaveRequestId(String LeaveRequestId);

	/**
	 * Returns the from addrs of this l m s mail notifications.
	 *
	 * @return the from addrs of this l m s mail notifications
	 */
	@AutoEscape
	public String getFromAddrs();

	/**
	 * Sets the from addrs of this l m s mail notifications.
	 *
	 * @param FromAddrs the from addrs of this l m s mail notifications
	 */
	public void setFromAddrs(String FromAddrs);

	/**
	 * Returns the to addrs of this l m s mail notifications.
	 *
	 * @return the to addrs of this l m s mail notifications
	 */
	@AutoEscape
	public String getToAddrs();

	/**
	 * Sets the to addrs of this l m s mail notifications.
	 *
	 * @param ToAddrs the to addrs of this l m s mail notifications
	 */
	public void setToAddrs(String ToAddrs);

	/**
	 * Returns the comments of this l m s mail notifications.
	 *
	 * @return the comments of this l m s mail notifications
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this l m s mail notifications.
	 *
	 * @param Comments the comments of this l m s mail notifications
	 */
	public void setComments(String Comments);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LMSMailNotifications lmsMailNotifications);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LMSMailNotifications> toCacheModel();

	@Override
	public LMSMailNotifications toEscapedModel();

	@Override
	public LMSMailNotifications toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}