/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the securaxEmployeeHrs service. Represents a row in the &quot;securaxEmployeeHrs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.securaxEmployeeHrsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.securaxEmployeeHrsImpl}.
 * </p>
 *
 * @author
 * @see securaxEmployeeHrs
 * @see com.trianz.lms.model.impl.securaxEmployeeHrsImpl
 * @see com.trianz.lms.model.impl.securaxEmployeeHrsModelImpl
 * @generated
 */
public interface securaxEmployeeHrsModel extends BaseModel<securaxEmployeeHrs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a securax employee hrs model instance should use the {@link securaxEmployeeHrs} interface instead.
	 */

	/**
	 * Returns the primary key of this securax employee hrs.
	 *
	 * @return the primary key of this securax employee hrs
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this securax employee hrs.
	 *
	 * @param primaryKey the primary key of this securax employee hrs
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the employee ID of this securax employee hrs.
	 *
	 * @return the employee ID of this securax employee hrs
	 */
	public int getEmployeeId();

	/**
	 * Sets the employee ID of this securax employee hrs.
	 *
	 * @param EmployeeId the employee ID of this securax employee hrs
	 */
	public void setEmployeeId(int EmployeeId);

	/**
	 * Returns the punch date of this securax employee hrs.
	 *
	 * @return the punch date of this securax employee hrs
	 */
	public Date getPunchDate();

	/**
	 * Sets the punch date of this securax employee hrs.
	 *
	 * @param PunchDate the punch date of this securax employee hrs
	 */
	public void setPunchDate(Date PunchDate);

	/**
	 * Returns the punch in time of this securax employee hrs.
	 *
	 * @return the punch in time of this securax employee hrs
	 */
	public Date getPunchInTime();

	/**
	 * Sets the punch in time of this securax employee hrs.
	 *
	 * @param PunchInTime the punch in time of this securax employee hrs
	 */
	public void setPunchInTime(Date PunchInTime);

	/**
	 * Returns the punch out time of this securax employee hrs.
	 *
	 * @return the punch out time of this securax employee hrs
	 */
	public Date getPunchOutTime();

	/**
	 * Sets the punch out time of this securax employee hrs.
	 *
	 * @param PunchOutTime the punch out time of this securax employee hrs
	 */
	public void setPunchOutTime(Date PunchOutTime);

	/**
	 * Returns the work hrs perday of this securax employee hrs.
	 *
	 * @return the work hrs perday of this securax employee hrs
	 */
	public Date getWorkHrsPerday();

	/**
	 * Sets the work hrs perday of this securax employee hrs.
	 *
	 * @param WorkHrsPerday the work hrs perday of this securax employee hrs
	 */
	public void setWorkHrsPerday(Date WorkHrsPerday);

	/**
	 * Returns the status of this securax employee hrs.
	 *
	 * @return the status of this securax employee hrs
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this securax employee hrs.
	 *
	 * @param Status the status of this securax employee hrs
	 */
	public void setStatus(String Status);

	/**
	 * Returns the o t of this securax employee hrs.
	 *
	 * @return the o t of this securax employee hrs
	 */
	public Date getOT();

	/**
	 * Sets the o t of this securax employee hrs.
	 *
	 * @param OT the o t of this securax employee hrs
	 */
	public void setOT(Date OT);

	/**
	 * Returns the created_ by of this securax employee hrs.
	 *
	 * @return the created_ by of this securax employee hrs
	 */
	public int getCreated_By();

	/**
	 * Sets the created_ by of this securax employee hrs.
	 *
	 * @param Created_By the created_ by of this securax employee hrs
	 */
	public void setCreated_By(int Created_By);

	/**
	 * Returns the created_ date of this securax employee hrs.
	 *
	 * @return the created_ date of this securax employee hrs
	 */
	public Date getCreated_Date();

	/**
	 * Sets the created_ date of this securax employee hrs.
	 *
	 * @param Created_Date the created_ date of this securax employee hrs
	 */
	public void setCreated_Date(Date Created_Date);

	/**
	 * Returns the modified_ by of this securax employee hrs.
	 *
	 * @return the modified_ by of this securax employee hrs
	 */
	public int getModified_By();

	/**
	 * Sets the modified_ by of this securax employee hrs.
	 *
	 * @param Modified_By the modified_ by of this securax employee hrs
	 */
	public void setModified_By(int Modified_By);

	/**
	 * Returns the modified_ date of this securax employee hrs.
	 *
	 * @return the modified_ date of this securax employee hrs
	 */
	public Date getModified_Date();

	/**
	 * Sets the modified_ date of this securax employee hrs.
	 *
	 * @param Modified_Date the modified_ date of this securax employee hrs
	 */
	public void setModified_Date(Date Modified_Date);

	/**
	 * Returns the s_ ID of this securax employee hrs.
	 *
	 * @return the s_ ID of this securax employee hrs
	 */
	public int getS_Id();

	/**
	 * Sets the s_ ID of this securax employee hrs.
	 *
	 * @param S_Id the s_ ID of this securax employee hrs
	 */
	public void setS_Id(int S_Id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(securaxEmployeeHrs securaxEmployeeHrs);

	@Override
	public int hashCode();

	@Override
	public CacheModel<securaxEmployeeHrs> toCacheModel();

	@Override
	public securaxEmployeeHrs toEscapedModel();

	@Override
	public securaxEmployeeHrs toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}