/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WFHManulPunch service. Represents a row in the &quot;WFHManulPunch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trianz.lms.model.impl.WFHManulPunchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trianz.lms.model.impl.WFHManulPunchImpl}.
 * </p>
 *
 * @author
 * @see WFHManulPunch
 * @see com.trianz.lms.model.impl.WFHManulPunchImpl
 * @see com.trianz.lms.model.impl.WFHManulPunchModelImpl
 * @generated
 */
public interface WFHManulPunchModel extends BaseModel<WFHManulPunch> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w f h manul punch model instance should use the {@link WFHManulPunch} interface instead.
	 */

	/**
	 * Returns the primary key of this w f h manul punch.
	 *
	 * @return the primary key of this w f h manul punch
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this w f h manul punch.
	 *
	 * @param primaryKey the primary key of this w f h manul punch
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the w f h manual punch ID of this w f h manul punch.
	 *
	 * @return the w f h manual punch ID of this w f h manul punch
	 */
	public int getWFHManualPunchId();

	/**
	 * Sets the w f h manual punch ID of this w f h manul punch.
	 *
	 * @param WFHManualPunchId the w f h manual punch ID of this w f h manul punch
	 */
	public void setWFHManualPunchId(int WFHManualPunchId);

	/**
	 * Returns the w f h i d of this w f h manul punch.
	 *
	 * @return the w f h i d of this w f h manul punch
	 */
	public int getWFHID();

	/**
	 * Sets the w f h i d of this w f h manul punch.
	 *
	 * @param WFHID the w f h i d of this w f h manul punch
	 */
	public void setWFHID(int WFHID);

	/**
	 * Returns the intime of this w f h manul punch.
	 *
	 * @return the intime of this w f h manul punch
	 */
	public Date getIntime();

	/**
	 * Sets the intime of this w f h manul punch.
	 *
	 * @param Intime the intime of this w f h manul punch
	 */
	public void setIntime(Date Intime);

	/**
	 * Returns the out time of this w f h manul punch.
	 *
	 * @return the out time of this w f h manul punch
	 */
	public Date getOutTime();

	/**
	 * Sets the out time of this w f h manul punch.
	 *
	 * @param OutTime the out time of this w f h manul punch
	 */
	public void setOutTime(Date OutTime);

	/**
	 * Returns the created by of this w f h manul punch.
	 *
	 * @return the created by of this w f h manul punch
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this w f h manul punch.
	 *
	 * @param CreatedBy the created by of this w f h manul punch
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this w f h manul punch.
	 *
	 * @return the created date of this w f h manul punch
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this w f h manul punch.
	 *
	 * @param CreatedDate the created date of this w f h manul punch
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this w f h manul punch.
	 *
	 * @return the modified by of this w f h manul punch
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this w f h manul punch.
	 *
	 * @param ModifiedBy the modified by of this w f h manul punch
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this w f h manul punch.
	 *
	 * @return the modified date of this w f h manul punch
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this w f h manul punch.
	 *
	 * @param ModifiedDate the modified date of this w f h manul punch
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the p u n c h d a t e of this w f h manul punch.
	 *
	 * @return the p u n c h d a t e of this w f h manul punch
	 */
	public Date getPUNCHDATE();

	/**
	 * Sets the p u n c h d a t e of this w f h manul punch.
	 *
	 * @param PUNCHDATE the p u n c h d a t e of this w f h manul punch
	 */
	public void setPUNCHDATE(Date PUNCHDATE);

	/**
	 * Returns the employee i d of this w f h manul punch.
	 *
	 * @return the employee i d of this w f h manul punch
	 */
	public int getEmployeeID();

	/**
	 * Sets the employee i d of this w f h manul punch.
	 *
	 * @param EmployeeID the employee i d of this w f h manul punch
	 */
	public void setEmployeeID(int EmployeeID);

	/**
	 * Returns the is approved of this w f h manul punch.
	 *
	 * @return the is approved of this w f h manul punch
	 */
	public boolean getIsApproved();

	/**
	 * Returns <code>true</code> if this w f h manul punch is is approved.
	 *
	 * @return <code>true</code> if this w f h manul punch is is approved; <code>false</code> otherwise
	 */
	public boolean isIsApproved();

	/**
	 * Sets whether this w f h manul punch is is approved.
	 *
	 * @param IsApproved the is approved of this w f h manul punch
	 */
	public void setIsApproved(boolean IsApproved);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WFHManulPunch wfhManulPunch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WFHManulPunch> toCacheModel();

	@Override
	public WFHManulPunch toEscapedModel();

	@Override
	public WFHManulPunch toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}