/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trianz.lms.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.trianz.lms.model.LMSProjectDetails;
import com.trianz.lms.service.LMSProjectDetailsService;
import com.trianz.lms.service.persistence.LMSCompOffLeaveDetailsPersistence;
import com.trianz.lms.service.persistence.LMSEmployeeDetailsPersistence;
import com.trianz.lms.service.persistence.LMSHolidaysPersistence;
import com.trianz.lms.service.persistence.LMSLeaveInformationPersistence;
import com.trianz.lms.service.persistence.LMSLeavePoliciesPersistence;
import com.trianz.lms.service.persistence.LMSLeaveTypePersistence;
import com.trianz.lms.service.persistence.LMSMailNotificationsPersistence;
import com.trianz.lms.service.persistence.LMSProjectDetailsPersistence;
import com.trianz.lms.service.persistence.LMSWeekendsPersistence;
import com.trianz.lms.service.persistence.LeaveApprovalHistoryPersistence;
import com.trianz.lms.service.persistence.LeaveBalancePersistence;
import com.trianz.lms.service.persistence.LeaveCategoriesPersistence;
import com.trianz.lms.service.persistence.LeaveInformationAuditPersistence;
import com.trianz.lms.service.persistence.WFHManulPunchPersistence;
import com.trianz.lms.service.persistence.securaxEmployeeHrsPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the l m s project details remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.trianz.lms.service.impl.LMSProjectDetailsServiceImpl}.
 * </p>
 *
 * @author
 * @see com.trianz.lms.service.impl.LMSProjectDetailsServiceImpl
 * @see com.trianz.lms.service.LMSProjectDetailsServiceUtil
 * @generated
 */
public abstract class LMSProjectDetailsServiceBaseImpl extends BaseServiceImpl
	implements LMSProjectDetailsService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.trianz.lms.service.LMSProjectDetailsServiceUtil} to access the l m s project details remote service.
	 */

	/**
	 * Returns the leave approval history local service.
	 *
	 * @return the leave approval history local service
	 */
	public com.trianz.lms.service.LeaveApprovalHistoryLocalService getLeaveApprovalHistoryLocalService() {
		return leaveApprovalHistoryLocalService;
	}

	/**
	 * Sets the leave approval history local service.
	 *
	 * @param leaveApprovalHistoryLocalService the leave approval history local service
	 */
	public void setLeaveApprovalHistoryLocalService(
		com.trianz.lms.service.LeaveApprovalHistoryLocalService leaveApprovalHistoryLocalService) {
		this.leaveApprovalHistoryLocalService = leaveApprovalHistoryLocalService;
	}

	/**
	 * Returns the leave approval history remote service.
	 *
	 * @return the leave approval history remote service
	 */
	public com.trianz.lms.service.LeaveApprovalHistoryService getLeaveApprovalHistoryService() {
		return leaveApprovalHistoryService;
	}

	/**
	 * Sets the leave approval history remote service.
	 *
	 * @param leaveApprovalHistoryService the leave approval history remote service
	 */
	public void setLeaveApprovalHistoryService(
		com.trianz.lms.service.LeaveApprovalHistoryService leaveApprovalHistoryService) {
		this.leaveApprovalHistoryService = leaveApprovalHistoryService;
	}

	/**
	 * Returns the leave approval history persistence.
	 *
	 * @return the leave approval history persistence
	 */
	public LeaveApprovalHistoryPersistence getLeaveApprovalHistoryPersistence() {
		return leaveApprovalHistoryPersistence;
	}

	/**
	 * Sets the leave approval history persistence.
	 *
	 * @param leaveApprovalHistoryPersistence the leave approval history persistence
	 */
	public void setLeaveApprovalHistoryPersistence(
		LeaveApprovalHistoryPersistence leaveApprovalHistoryPersistence) {
		this.leaveApprovalHistoryPersistence = leaveApprovalHistoryPersistence;
	}

	/**
	 * Returns the leave balance local service.
	 *
	 * @return the leave balance local service
	 */
	public com.trianz.lms.service.LeaveBalanceLocalService getLeaveBalanceLocalService() {
		return leaveBalanceLocalService;
	}

	/**
	 * Sets the leave balance local service.
	 *
	 * @param leaveBalanceLocalService the leave balance local service
	 */
	public void setLeaveBalanceLocalService(
		com.trianz.lms.service.LeaveBalanceLocalService leaveBalanceLocalService) {
		this.leaveBalanceLocalService = leaveBalanceLocalService;
	}

	/**
	 * Returns the leave balance remote service.
	 *
	 * @return the leave balance remote service
	 */
	public com.trianz.lms.service.LeaveBalanceService getLeaveBalanceService() {
		return leaveBalanceService;
	}

	/**
	 * Sets the leave balance remote service.
	 *
	 * @param leaveBalanceService the leave balance remote service
	 */
	public void setLeaveBalanceService(
		com.trianz.lms.service.LeaveBalanceService leaveBalanceService) {
		this.leaveBalanceService = leaveBalanceService;
	}

	/**
	 * Returns the leave balance persistence.
	 *
	 * @return the leave balance persistence
	 */
	public LeaveBalancePersistence getLeaveBalancePersistence() {
		return leaveBalancePersistence;
	}

	/**
	 * Sets the leave balance persistence.
	 *
	 * @param leaveBalancePersistence the leave balance persistence
	 */
	public void setLeaveBalancePersistence(
		LeaveBalancePersistence leaveBalancePersistence) {
		this.leaveBalancePersistence = leaveBalancePersistence;
	}

	/**
	 * Returns the leave categories local service.
	 *
	 * @return the leave categories local service
	 */
	public com.trianz.lms.service.LeaveCategoriesLocalService getLeaveCategoriesLocalService() {
		return leaveCategoriesLocalService;
	}

	/**
	 * Sets the leave categories local service.
	 *
	 * @param leaveCategoriesLocalService the leave categories local service
	 */
	public void setLeaveCategoriesLocalService(
		com.trianz.lms.service.LeaveCategoriesLocalService leaveCategoriesLocalService) {
		this.leaveCategoriesLocalService = leaveCategoriesLocalService;
	}

	/**
	 * Returns the leave categories remote service.
	 *
	 * @return the leave categories remote service
	 */
	public com.trianz.lms.service.LeaveCategoriesService getLeaveCategoriesService() {
		return leaveCategoriesService;
	}

	/**
	 * Sets the leave categories remote service.
	 *
	 * @param leaveCategoriesService the leave categories remote service
	 */
	public void setLeaveCategoriesService(
		com.trianz.lms.service.LeaveCategoriesService leaveCategoriesService) {
		this.leaveCategoriesService = leaveCategoriesService;
	}

	/**
	 * Returns the leave categories persistence.
	 *
	 * @return the leave categories persistence
	 */
	public LeaveCategoriesPersistence getLeaveCategoriesPersistence() {
		return leaveCategoriesPersistence;
	}

	/**
	 * Sets the leave categories persistence.
	 *
	 * @param leaveCategoriesPersistence the leave categories persistence
	 */
	public void setLeaveCategoriesPersistence(
		LeaveCategoriesPersistence leaveCategoriesPersistence) {
		this.leaveCategoriesPersistence = leaveCategoriesPersistence;
	}

	/**
	 * Returns the leave information audit local service.
	 *
	 * @return the leave information audit local service
	 */
	public com.trianz.lms.service.LeaveInformationAuditLocalService getLeaveInformationAuditLocalService() {
		return leaveInformationAuditLocalService;
	}

	/**
	 * Sets the leave information audit local service.
	 *
	 * @param leaveInformationAuditLocalService the leave information audit local service
	 */
	public void setLeaveInformationAuditLocalService(
		com.trianz.lms.service.LeaveInformationAuditLocalService leaveInformationAuditLocalService) {
		this.leaveInformationAuditLocalService = leaveInformationAuditLocalService;
	}

	/**
	 * Returns the leave information audit remote service.
	 *
	 * @return the leave information audit remote service
	 */
	public com.trianz.lms.service.LeaveInformationAuditService getLeaveInformationAuditService() {
		return leaveInformationAuditService;
	}

	/**
	 * Sets the leave information audit remote service.
	 *
	 * @param leaveInformationAuditService the leave information audit remote service
	 */
	public void setLeaveInformationAuditService(
		com.trianz.lms.service.LeaveInformationAuditService leaveInformationAuditService) {
		this.leaveInformationAuditService = leaveInformationAuditService;
	}

	/**
	 * Returns the leave information audit persistence.
	 *
	 * @return the leave information audit persistence
	 */
	public LeaveInformationAuditPersistence getLeaveInformationAuditPersistence() {
		return leaveInformationAuditPersistence;
	}

	/**
	 * Sets the leave information audit persistence.
	 *
	 * @param leaveInformationAuditPersistence the leave information audit persistence
	 */
	public void setLeaveInformationAuditPersistence(
		LeaveInformationAuditPersistence leaveInformationAuditPersistence) {
		this.leaveInformationAuditPersistence = leaveInformationAuditPersistence;
	}

	/**
	 * Returns the l m s comp off leave details local service.
	 *
	 * @return the l m s comp off leave details local service
	 */
	public com.trianz.lms.service.LMSCompOffLeaveDetailsLocalService getLMSCompOffLeaveDetailsLocalService() {
		return lmsCompOffLeaveDetailsLocalService;
	}

	/**
	 * Sets the l m s comp off leave details local service.
	 *
	 * @param lmsCompOffLeaveDetailsLocalService the l m s comp off leave details local service
	 */
	public void setLMSCompOffLeaveDetailsLocalService(
		com.trianz.lms.service.LMSCompOffLeaveDetailsLocalService lmsCompOffLeaveDetailsLocalService) {
		this.lmsCompOffLeaveDetailsLocalService = lmsCompOffLeaveDetailsLocalService;
	}

	/**
	 * Returns the l m s comp off leave details remote service.
	 *
	 * @return the l m s comp off leave details remote service
	 */
	public com.trianz.lms.service.LMSCompOffLeaveDetailsService getLMSCompOffLeaveDetailsService() {
		return lmsCompOffLeaveDetailsService;
	}

	/**
	 * Sets the l m s comp off leave details remote service.
	 *
	 * @param lmsCompOffLeaveDetailsService the l m s comp off leave details remote service
	 */
	public void setLMSCompOffLeaveDetailsService(
		com.trianz.lms.service.LMSCompOffLeaveDetailsService lmsCompOffLeaveDetailsService) {
		this.lmsCompOffLeaveDetailsService = lmsCompOffLeaveDetailsService;
	}

	/**
	 * Returns the l m s comp off leave details persistence.
	 *
	 * @return the l m s comp off leave details persistence
	 */
	public LMSCompOffLeaveDetailsPersistence getLMSCompOffLeaveDetailsPersistence() {
		return lmsCompOffLeaveDetailsPersistence;
	}

	/**
	 * Sets the l m s comp off leave details persistence.
	 *
	 * @param lmsCompOffLeaveDetailsPersistence the l m s comp off leave details persistence
	 */
	public void setLMSCompOffLeaveDetailsPersistence(
		LMSCompOffLeaveDetailsPersistence lmsCompOffLeaveDetailsPersistence) {
		this.lmsCompOffLeaveDetailsPersistence = lmsCompOffLeaveDetailsPersistence;
	}

	/**
	 * Returns the l m s employee details local service.
	 *
	 * @return the l m s employee details local service
	 */
	public com.trianz.lms.service.LMSEmployeeDetailsLocalService getLMSEmployeeDetailsLocalService() {
		return lmsEmployeeDetailsLocalService;
	}

	/**
	 * Sets the l m s employee details local service.
	 *
	 * @param lmsEmployeeDetailsLocalService the l m s employee details local service
	 */
	public void setLMSEmployeeDetailsLocalService(
		com.trianz.lms.service.LMSEmployeeDetailsLocalService lmsEmployeeDetailsLocalService) {
		this.lmsEmployeeDetailsLocalService = lmsEmployeeDetailsLocalService;
	}

	/**
	 * Returns the l m s employee details remote service.
	 *
	 * @return the l m s employee details remote service
	 */
	public com.trianz.lms.service.LMSEmployeeDetailsService getLMSEmployeeDetailsService() {
		return lmsEmployeeDetailsService;
	}

	/**
	 * Sets the l m s employee details remote service.
	 *
	 * @param lmsEmployeeDetailsService the l m s employee details remote service
	 */
	public void setLMSEmployeeDetailsService(
		com.trianz.lms.service.LMSEmployeeDetailsService lmsEmployeeDetailsService) {
		this.lmsEmployeeDetailsService = lmsEmployeeDetailsService;
	}

	/**
	 * Returns the l m s employee details persistence.
	 *
	 * @return the l m s employee details persistence
	 */
	public LMSEmployeeDetailsPersistence getLMSEmployeeDetailsPersistence() {
		return lmsEmployeeDetailsPersistence;
	}

	/**
	 * Sets the l m s employee details persistence.
	 *
	 * @param lmsEmployeeDetailsPersistence the l m s employee details persistence
	 */
	public void setLMSEmployeeDetailsPersistence(
		LMSEmployeeDetailsPersistence lmsEmployeeDetailsPersistence) {
		this.lmsEmployeeDetailsPersistence = lmsEmployeeDetailsPersistence;
	}

	/**
	 * Returns the l m s holidays local service.
	 *
	 * @return the l m s holidays local service
	 */
	public com.trianz.lms.service.LMSHolidaysLocalService getLMSHolidaysLocalService() {
		return lmsHolidaysLocalService;
	}

	/**
	 * Sets the l m s holidays local service.
	 *
	 * @param lmsHolidaysLocalService the l m s holidays local service
	 */
	public void setLMSHolidaysLocalService(
		com.trianz.lms.service.LMSHolidaysLocalService lmsHolidaysLocalService) {
		this.lmsHolidaysLocalService = lmsHolidaysLocalService;
	}

	/**
	 * Returns the l m s holidays remote service.
	 *
	 * @return the l m s holidays remote service
	 */
	public com.trianz.lms.service.LMSHolidaysService getLMSHolidaysService() {
		return lmsHolidaysService;
	}

	/**
	 * Sets the l m s holidays remote service.
	 *
	 * @param lmsHolidaysService the l m s holidays remote service
	 */
	public void setLMSHolidaysService(
		com.trianz.lms.service.LMSHolidaysService lmsHolidaysService) {
		this.lmsHolidaysService = lmsHolidaysService;
	}

	/**
	 * Returns the l m s holidays persistence.
	 *
	 * @return the l m s holidays persistence
	 */
	public LMSHolidaysPersistence getLMSHolidaysPersistence() {
		return lmsHolidaysPersistence;
	}

	/**
	 * Sets the l m s holidays persistence.
	 *
	 * @param lmsHolidaysPersistence the l m s holidays persistence
	 */
	public void setLMSHolidaysPersistence(
		LMSHolidaysPersistence lmsHolidaysPersistence) {
		this.lmsHolidaysPersistence = lmsHolidaysPersistence;
	}

	/**
	 * Returns the l m s leave information local service.
	 *
	 * @return the l m s leave information local service
	 */
	public com.trianz.lms.service.LMSLeaveInformationLocalService getLMSLeaveInformationLocalService() {
		return lmsLeaveInformationLocalService;
	}

	/**
	 * Sets the l m s leave information local service.
	 *
	 * @param lmsLeaveInformationLocalService the l m s leave information local service
	 */
	public void setLMSLeaveInformationLocalService(
		com.trianz.lms.service.LMSLeaveInformationLocalService lmsLeaveInformationLocalService) {
		this.lmsLeaveInformationLocalService = lmsLeaveInformationLocalService;
	}

	/**
	 * Returns the l m s leave information remote service.
	 *
	 * @return the l m s leave information remote service
	 */
	public com.trianz.lms.service.LMSLeaveInformationService getLMSLeaveInformationService() {
		return lmsLeaveInformationService;
	}

	/**
	 * Sets the l m s leave information remote service.
	 *
	 * @param lmsLeaveInformationService the l m s leave information remote service
	 */
	public void setLMSLeaveInformationService(
		com.trianz.lms.service.LMSLeaveInformationService lmsLeaveInformationService) {
		this.lmsLeaveInformationService = lmsLeaveInformationService;
	}

	/**
	 * Returns the l m s leave information persistence.
	 *
	 * @return the l m s leave information persistence
	 */
	public LMSLeaveInformationPersistence getLMSLeaveInformationPersistence() {
		return lmsLeaveInformationPersistence;
	}

	/**
	 * Sets the l m s leave information persistence.
	 *
	 * @param lmsLeaveInformationPersistence the l m s leave information persistence
	 */
	public void setLMSLeaveInformationPersistence(
		LMSLeaveInformationPersistence lmsLeaveInformationPersistence) {
		this.lmsLeaveInformationPersistence = lmsLeaveInformationPersistence;
	}

	/**
	 * Returns the l m s leave policies local service.
	 *
	 * @return the l m s leave policies local service
	 */
	public com.trianz.lms.service.LMSLeavePoliciesLocalService getLMSLeavePoliciesLocalService() {
		return lmsLeavePoliciesLocalService;
	}

	/**
	 * Sets the l m s leave policies local service.
	 *
	 * @param lmsLeavePoliciesLocalService the l m s leave policies local service
	 */
	public void setLMSLeavePoliciesLocalService(
		com.trianz.lms.service.LMSLeavePoliciesLocalService lmsLeavePoliciesLocalService) {
		this.lmsLeavePoliciesLocalService = lmsLeavePoliciesLocalService;
	}

	/**
	 * Returns the l m s leave policies remote service.
	 *
	 * @return the l m s leave policies remote service
	 */
	public com.trianz.lms.service.LMSLeavePoliciesService getLMSLeavePoliciesService() {
		return lmsLeavePoliciesService;
	}

	/**
	 * Sets the l m s leave policies remote service.
	 *
	 * @param lmsLeavePoliciesService the l m s leave policies remote service
	 */
	public void setLMSLeavePoliciesService(
		com.trianz.lms.service.LMSLeavePoliciesService lmsLeavePoliciesService) {
		this.lmsLeavePoliciesService = lmsLeavePoliciesService;
	}

	/**
	 * Returns the l m s leave policies persistence.
	 *
	 * @return the l m s leave policies persistence
	 */
	public LMSLeavePoliciesPersistence getLMSLeavePoliciesPersistence() {
		return lmsLeavePoliciesPersistence;
	}

	/**
	 * Sets the l m s leave policies persistence.
	 *
	 * @param lmsLeavePoliciesPersistence the l m s leave policies persistence
	 */
	public void setLMSLeavePoliciesPersistence(
		LMSLeavePoliciesPersistence lmsLeavePoliciesPersistence) {
		this.lmsLeavePoliciesPersistence = lmsLeavePoliciesPersistence;
	}

	/**
	 * Returns the l m s leave type local service.
	 *
	 * @return the l m s leave type local service
	 */
	public com.trianz.lms.service.LMSLeaveTypeLocalService getLMSLeaveTypeLocalService() {
		return lmsLeaveTypeLocalService;
	}

	/**
	 * Sets the l m s leave type local service.
	 *
	 * @param lmsLeaveTypeLocalService the l m s leave type local service
	 */
	public void setLMSLeaveTypeLocalService(
		com.trianz.lms.service.LMSLeaveTypeLocalService lmsLeaveTypeLocalService) {
		this.lmsLeaveTypeLocalService = lmsLeaveTypeLocalService;
	}

	/**
	 * Returns the l m s leave type remote service.
	 *
	 * @return the l m s leave type remote service
	 */
	public com.trianz.lms.service.LMSLeaveTypeService getLMSLeaveTypeService() {
		return lmsLeaveTypeService;
	}

	/**
	 * Sets the l m s leave type remote service.
	 *
	 * @param lmsLeaveTypeService the l m s leave type remote service
	 */
	public void setLMSLeaveTypeService(
		com.trianz.lms.service.LMSLeaveTypeService lmsLeaveTypeService) {
		this.lmsLeaveTypeService = lmsLeaveTypeService;
	}

	/**
	 * Returns the l m s leave type persistence.
	 *
	 * @return the l m s leave type persistence
	 */
	public LMSLeaveTypePersistence getLMSLeaveTypePersistence() {
		return lmsLeaveTypePersistence;
	}

	/**
	 * Sets the l m s leave type persistence.
	 *
	 * @param lmsLeaveTypePersistence the l m s leave type persistence
	 */
	public void setLMSLeaveTypePersistence(
		LMSLeaveTypePersistence lmsLeaveTypePersistence) {
		this.lmsLeaveTypePersistence = lmsLeaveTypePersistence;
	}

	/**
	 * Returns the l m s mail notifications local service.
	 *
	 * @return the l m s mail notifications local service
	 */
	public com.trianz.lms.service.LMSMailNotificationsLocalService getLMSMailNotificationsLocalService() {
		return lmsMailNotificationsLocalService;
	}

	/**
	 * Sets the l m s mail notifications local service.
	 *
	 * @param lmsMailNotificationsLocalService the l m s mail notifications local service
	 */
	public void setLMSMailNotificationsLocalService(
		com.trianz.lms.service.LMSMailNotificationsLocalService lmsMailNotificationsLocalService) {
		this.lmsMailNotificationsLocalService = lmsMailNotificationsLocalService;
	}

	/**
	 * Returns the l m s mail notifications remote service.
	 *
	 * @return the l m s mail notifications remote service
	 */
	public com.trianz.lms.service.LMSMailNotificationsService getLMSMailNotificationsService() {
		return lmsMailNotificationsService;
	}

	/**
	 * Sets the l m s mail notifications remote service.
	 *
	 * @param lmsMailNotificationsService the l m s mail notifications remote service
	 */
	public void setLMSMailNotificationsService(
		com.trianz.lms.service.LMSMailNotificationsService lmsMailNotificationsService) {
		this.lmsMailNotificationsService = lmsMailNotificationsService;
	}

	/**
	 * Returns the l m s mail notifications persistence.
	 *
	 * @return the l m s mail notifications persistence
	 */
	public LMSMailNotificationsPersistence getLMSMailNotificationsPersistence() {
		return lmsMailNotificationsPersistence;
	}

	/**
	 * Sets the l m s mail notifications persistence.
	 *
	 * @param lmsMailNotificationsPersistence the l m s mail notifications persistence
	 */
	public void setLMSMailNotificationsPersistence(
		LMSMailNotificationsPersistence lmsMailNotificationsPersistence) {
		this.lmsMailNotificationsPersistence = lmsMailNotificationsPersistence;
	}

	/**
	 * Returns the l m s project details local service.
	 *
	 * @return the l m s project details local service
	 */
	public com.trianz.lms.service.LMSProjectDetailsLocalService getLMSProjectDetailsLocalService() {
		return lmsProjectDetailsLocalService;
	}

	/**
	 * Sets the l m s project details local service.
	 *
	 * @param lmsProjectDetailsLocalService the l m s project details local service
	 */
	public void setLMSProjectDetailsLocalService(
		com.trianz.lms.service.LMSProjectDetailsLocalService lmsProjectDetailsLocalService) {
		this.lmsProjectDetailsLocalService = lmsProjectDetailsLocalService;
	}

	/**
	 * Returns the l m s project details remote service.
	 *
	 * @return the l m s project details remote service
	 */
	public com.trianz.lms.service.LMSProjectDetailsService getLMSProjectDetailsService() {
		return lmsProjectDetailsService;
	}

	/**
	 * Sets the l m s project details remote service.
	 *
	 * @param lmsProjectDetailsService the l m s project details remote service
	 */
	public void setLMSProjectDetailsService(
		com.trianz.lms.service.LMSProjectDetailsService lmsProjectDetailsService) {
		this.lmsProjectDetailsService = lmsProjectDetailsService;
	}

	/**
	 * Returns the l m s project details persistence.
	 *
	 * @return the l m s project details persistence
	 */
	public LMSProjectDetailsPersistence getLMSProjectDetailsPersistence() {
		return lmsProjectDetailsPersistence;
	}

	/**
	 * Sets the l m s project details persistence.
	 *
	 * @param lmsProjectDetailsPersistence the l m s project details persistence
	 */
	public void setLMSProjectDetailsPersistence(
		LMSProjectDetailsPersistence lmsProjectDetailsPersistence) {
		this.lmsProjectDetailsPersistence = lmsProjectDetailsPersistence;
	}

	/**
	 * Returns the l m s weekends local service.
	 *
	 * @return the l m s weekends local service
	 */
	public com.trianz.lms.service.LMSWeekendsLocalService getLMSWeekendsLocalService() {
		return lmsWeekendsLocalService;
	}

	/**
	 * Sets the l m s weekends local service.
	 *
	 * @param lmsWeekendsLocalService the l m s weekends local service
	 */
	public void setLMSWeekendsLocalService(
		com.trianz.lms.service.LMSWeekendsLocalService lmsWeekendsLocalService) {
		this.lmsWeekendsLocalService = lmsWeekendsLocalService;
	}

	/**
	 * Returns the l m s weekends remote service.
	 *
	 * @return the l m s weekends remote service
	 */
	public com.trianz.lms.service.LMSWeekendsService getLMSWeekendsService() {
		return lmsWeekendsService;
	}

	/**
	 * Sets the l m s weekends remote service.
	 *
	 * @param lmsWeekendsService the l m s weekends remote service
	 */
	public void setLMSWeekendsService(
		com.trianz.lms.service.LMSWeekendsService lmsWeekendsService) {
		this.lmsWeekendsService = lmsWeekendsService;
	}

	/**
	 * Returns the l m s weekends persistence.
	 *
	 * @return the l m s weekends persistence
	 */
	public LMSWeekendsPersistence getLMSWeekendsPersistence() {
		return lmsWeekendsPersistence;
	}

	/**
	 * Sets the l m s weekends persistence.
	 *
	 * @param lmsWeekendsPersistence the l m s weekends persistence
	 */
	public void setLMSWeekendsPersistence(
		LMSWeekendsPersistence lmsWeekendsPersistence) {
		this.lmsWeekendsPersistence = lmsWeekendsPersistence;
	}

	/**
	 * Returns the securax employee hrs local service.
	 *
	 * @return the securax employee hrs local service
	 */
	public com.trianz.lms.service.securaxEmployeeHrsLocalService getsecuraxEmployeeHrsLocalService() {
		return securaxEmployeeHrsLocalService;
	}

	/**
	 * Sets the securax employee hrs local service.
	 *
	 * @param securaxEmployeeHrsLocalService the securax employee hrs local service
	 */
	public void setsecuraxEmployeeHrsLocalService(
		com.trianz.lms.service.securaxEmployeeHrsLocalService securaxEmployeeHrsLocalService) {
		this.securaxEmployeeHrsLocalService = securaxEmployeeHrsLocalService;
	}

	/**
	 * Returns the securax employee hrs remote service.
	 *
	 * @return the securax employee hrs remote service
	 */
	public com.trianz.lms.service.securaxEmployeeHrsService getsecuraxEmployeeHrsService() {
		return securaxEmployeeHrsService;
	}

	/**
	 * Sets the securax employee hrs remote service.
	 *
	 * @param securaxEmployeeHrsService the securax employee hrs remote service
	 */
	public void setsecuraxEmployeeHrsService(
		com.trianz.lms.service.securaxEmployeeHrsService securaxEmployeeHrsService) {
		this.securaxEmployeeHrsService = securaxEmployeeHrsService;
	}

	/**
	 * Returns the securax employee hrs persistence.
	 *
	 * @return the securax employee hrs persistence
	 */
	public securaxEmployeeHrsPersistence getsecuraxEmployeeHrsPersistence() {
		return securaxEmployeeHrsPersistence;
	}

	/**
	 * Sets the securax employee hrs persistence.
	 *
	 * @param securaxEmployeeHrsPersistence the securax employee hrs persistence
	 */
	public void setsecuraxEmployeeHrsPersistence(
		securaxEmployeeHrsPersistence securaxEmployeeHrsPersistence) {
		this.securaxEmployeeHrsPersistence = securaxEmployeeHrsPersistence;
	}

	/**
	 * Returns the w f h manul punch local service.
	 *
	 * @return the w f h manul punch local service
	 */
	public com.trianz.lms.service.WFHManulPunchLocalService getWFHManulPunchLocalService() {
		return wfhManulPunchLocalService;
	}

	/**
	 * Sets the w f h manul punch local service.
	 *
	 * @param wfhManulPunchLocalService the w f h manul punch local service
	 */
	public void setWFHManulPunchLocalService(
		com.trianz.lms.service.WFHManulPunchLocalService wfhManulPunchLocalService) {
		this.wfhManulPunchLocalService = wfhManulPunchLocalService;
	}

	/**
	 * Returns the w f h manul punch remote service.
	 *
	 * @return the w f h manul punch remote service
	 */
	public com.trianz.lms.service.WFHManulPunchService getWFHManulPunchService() {
		return wfhManulPunchService;
	}

	/**
	 * Sets the w f h manul punch remote service.
	 *
	 * @param wfhManulPunchService the w f h manul punch remote service
	 */
	public void setWFHManulPunchService(
		com.trianz.lms.service.WFHManulPunchService wfhManulPunchService) {
		this.wfhManulPunchService = wfhManulPunchService;
	}

	/**
	 * Returns the w f h manul punch persistence.
	 *
	 * @return the w f h manul punch persistence
	 */
	public WFHManulPunchPersistence getWFHManulPunchPersistence() {
		return wfhManulPunchPersistence;
	}

	/**
	 * Sets the w f h manul punch persistence.
	 *
	 * @param wfhManulPunchPersistence the w f h manul punch persistence
	 */
	public void setWFHManulPunchPersistence(
		WFHManulPunchPersistence wfhManulPunchPersistence) {
		this.wfhManulPunchPersistence = wfhManulPunchPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return LMSProjectDetails.class;
	}

	protected String getModelClassName() {
		return LMSProjectDetails.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = lmsProjectDetailsPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.trianz.lms.service.LeaveApprovalHistoryLocalService.class)
	protected com.trianz.lms.service.LeaveApprovalHistoryLocalService leaveApprovalHistoryLocalService;
	@BeanReference(type = com.trianz.lms.service.LeaveApprovalHistoryService.class)
	protected com.trianz.lms.service.LeaveApprovalHistoryService leaveApprovalHistoryService;
	@BeanReference(type = LeaveApprovalHistoryPersistence.class)
	protected LeaveApprovalHistoryPersistence leaveApprovalHistoryPersistence;
	@BeanReference(type = com.trianz.lms.service.LeaveBalanceLocalService.class)
	protected com.trianz.lms.service.LeaveBalanceLocalService leaveBalanceLocalService;
	@BeanReference(type = com.trianz.lms.service.LeaveBalanceService.class)
	protected com.trianz.lms.service.LeaveBalanceService leaveBalanceService;
	@BeanReference(type = LeaveBalancePersistence.class)
	protected LeaveBalancePersistence leaveBalancePersistence;
	@BeanReference(type = com.trianz.lms.service.LeaveCategoriesLocalService.class)
	protected com.trianz.lms.service.LeaveCategoriesLocalService leaveCategoriesLocalService;
	@BeanReference(type = com.trianz.lms.service.LeaveCategoriesService.class)
	protected com.trianz.lms.service.LeaveCategoriesService leaveCategoriesService;
	@BeanReference(type = LeaveCategoriesPersistence.class)
	protected LeaveCategoriesPersistence leaveCategoriesPersistence;
	@BeanReference(type = com.trianz.lms.service.LeaveInformationAuditLocalService.class)
	protected com.trianz.lms.service.LeaveInformationAuditLocalService leaveInformationAuditLocalService;
	@BeanReference(type = com.trianz.lms.service.LeaveInformationAuditService.class)
	protected com.trianz.lms.service.LeaveInformationAuditService leaveInformationAuditService;
	@BeanReference(type = LeaveInformationAuditPersistence.class)
	protected LeaveInformationAuditPersistence leaveInformationAuditPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSCompOffLeaveDetailsLocalService.class)
	protected com.trianz.lms.service.LMSCompOffLeaveDetailsLocalService lmsCompOffLeaveDetailsLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSCompOffLeaveDetailsService.class)
	protected com.trianz.lms.service.LMSCompOffLeaveDetailsService lmsCompOffLeaveDetailsService;
	@BeanReference(type = LMSCompOffLeaveDetailsPersistence.class)
	protected LMSCompOffLeaveDetailsPersistence lmsCompOffLeaveDetailsPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSEmployeeDetailsLocalService.class)
	protected com.trianz.lms.service.LMSEmployeeDetailsLocalService lmsEmployeeDetailsLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSEmployeeDetailsService.class)
	protected com.trianz.lms.service.LMSEmployeeDetailsService lmsEmployeeDetailsService;
	@BeanReference(type = LMSEmployeeDetailsPersistence.class)
	protected LMSEmployeeDetailsPersistence lmsEmployeeDetailsPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSHolidaysLocalService.class)
	protected com.trianz.lms.service.LMSHolidaysLocalService lmsHolidaysLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSHolidaysService.class)
	protected com.trianz.lms.service.LMSHolidaysService lmsHolidaysService;
	@BeanReference(type = LMSHolidaysPersistence.class)
	protected LMSHolidaysPersistence lmsHolidaysPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSLeaveInformationLocalService.class)
	protected com.trianz.lms.service.LMSLeaveInformationLocalService lmsLeaveInformationLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSLeaveInformationService.class)
	protected com.trianz.lms.service.LMSLeaveInformationService lmsLeaveInformationService;
	@BeanReference(type = LMSLeaveInformationPersistence.class)
	protected LMSLeaveInformationPersistence lmsLeaveInformationPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSLeavePoliciesLocalService.class)
	protected com.trianz.lms.service.LMSLeavePoliciesLocalService lmsLeavePoliciesLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSLeavePoliciesService.class)
	protected com.trianz.lms.service.LMSLeavePoliciesService lmsLeavePoliciesService;
	@BeanReference(type = LMSLeavePoliciesPersistence.class)
	protected LMSLeavePoliciesPersistence lmsLeavePoliciesPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSLeaveTypeLocalService.class)
	protected com.trianz.lms.service.LMSLeaveTypeLocalService lmsLeaveTypeLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSLeaveTypeService.class)
	protected com.trianz.lms.service.LMSLeaveTypeService lmsLeaveTypeService;
	@BeanReference(type = LMSLeaveTypePersistence.class)
	protected LMSLeaveTypePersistence lmsLeaveTypePersistence;
	@BeanReference(type = com.trianz.lms.service.LMSMailNotificationsLocalService.class)
	protected com.trianz.lms.service.LMSMailNotificationsLocalService lmsMailNotificationsLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSMailNotificationsService.class)
	protected com.trianz.lms.service.LMSMailNotificationsService lmsMailNotificationsService;
	@BeanReference(type = LMSMailNotificationsPersistence.class)
	protected LMSMailNotificationsPersistence lmsMailNotificationsPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSProjectDetailsLocalService.class)
	protected com.trianz.lms.service.LMSProjectDetailsLocalService lmsProjectDetailsLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSProjectDetailsService.class)
	protected com.trianz.lms.service.LMSProjectDetailsService lmsProjectDetailsService;
	@BeanReference(type = LMSProjectDetailsPersistence.class)
	protected LMSProjectDetailsPersistence lmsProjectDetailsPersistence;
	@BeanReference(type = com.trianz.lms.service.LMSWeekendsLocalService.class)
	protected com.trianz.lms.service.LMSWeekendsLocalService lmsWeekendsLocalService;
	@BeanReference(type = com.trianz.lms.service.LMSWeekendsService.class)
	protected com.trianz.lms.service.LMSWeekendsService lmsWeekendsService;
	@BeanReference(type = LMSWeekendsPersistence.class)
	protected LMSWeekendsPersistence lmsWeekendsPersistence;
	@BeanReference(type = com.trianz.lms.service.securaxEmployeeHrsLocalService.class)
	protected com.trianz.lms.service.securaxEmployeeHrsLocalService securaxEmployeeHrsLocalService;
	@BeanReference(type = com.trianz.lms.service.securaxEmployeeHrsService.class)
	protected com.trianz.lms.service.securaxEmployeeHrsService securaxEmployeeHrsService;
	@BeanReference(type = securaxEmployeeHrsPersistence.class)
	protected securaxEmployeeHrsPersistence securaxEmployeeHrsPersistence;
	@BeanReference(type = com.trianz.lms.service.WFHManulPunchLocalService.class)
	protected com.trianz.lms.service.WFHManulPunchLocalService wfhManulPunchLocalService;
	@BeanReference(type = com.trianz.lms.service.WFHManulPunchService.class)
	protected com.trianz.lms.service.WFHManulPunchService wfhManulPunchService;
	@BeanReference(type = WFHManulPunchPersistence.class)
	protected WFHManulPunchPersistence wfhManulPunchPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LMSProjectDetailsServiceClpInvoker _clpInvoker = new LMSProjectDetailsServiceClpInvoker();
}